[package]
name = "fernschreiber"
version = "0.2.3"
authors = ["Maximilian Güntner <maximilian@buzzn.net>"]

[dependencies]
rocket = "0.4"
multipart = "0.15.2"
encoding = "0.2.33"
chrono = "0.4"
mime = "^0.3"
tempfile = "3"
uuid = { version = "^0.6", features = ["v4"] }
native-tls = { version = "^0.2" }

[dependencies.lettre]
git = "https://github.com/buzzn/lettre.git"
rev = "fc7edc97796f88990a2954d2f468715dbf46c9d9"

[dependencies.lettre_email]
git = "https://github.com/buzzn/lettre.git"
rev = "fc7edc97796f88990a2954d2f468715dbf46c9d9"
